"use client";

import React, { useState, useEffect } from "react";
import { motion, Variants } from "framer-motion";
import { CalendarCheck, CheckCircle, XCircle, Clock, MapPin, IndianRupee, UserCircle, Users, FileText, FileSpreadsheet } from "lucide-react";
import { supabase } from "@/app/student/supabase";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function HODEventsApprovals() {
  const [hodData, setHodData] = useState<any>(null);
  const [proposals, setProposals] = useState<any[]>([]);
  const [activeTab, setActiveTab] = useState<"pending" | "approved" | "rejected">("pending");
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      const huid = localStorage.getItem("campuspulse_uid");
      if (!huid) return;

      const { data: hod } = await supabase
        .from("hods")
        .select("*")
        .eq("huid", huid)
        .single();

      if (hod) {
        setHodData(hod);
        
        // Fetch ALL event proposals for this department
        const { data: events } = await supabase
          .from("event_proposals")
          .select("*")
          .eq("department_id", String(hod.department_id))
          .order("created_at", { ascending: false });
          
        if (events) setProposals(events);
      }
    } catch (error) {
      console.error("Fetch Error:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleApprovalAction = async (id: string, newStatus: "approved" | "rejected") => {
    const confirmMsg = newStatus === "approved" ? "Approve this event?" : "Reject this event?";
    if (!window.confirm(confirmMsg)) return;

    try {
      const { error } = await supabase
        .from("event_proposals")
        .update({ status: newStatus })
        .eq("id", id);

      if (error) throw error;

      // Update local state so it immediately moves to the correct tab
      setProposals((prev) => 
        prev.map((p) => (p.id === id ? { ...p, status: newStatus } : p))
      );
      
      alert(`Event has been ${newStatus}!`);
    } catch (error: any) {
      alert("Error updating proposal: " + error.message);
    }
  };

  const filteredProposals = proposals.filter((p) => p.status === activeTab);

  // --- PDF Export Logic ---
  const handleExportPDF = () => {
    if (filteredProposals.length === 0) {
      alert(`No ${activeTab} proposals to export.`);
      return;
    }

    const doc = new jsPDF("landscape"); // Landscape for wider tables
    
    doc.setFontSize(18);
    doc.text(`Event Proposals Report - ${activeTab.toUpperCase()}`, 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated by CampusPulse`, 14, 30);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 14, 36);

    const tableData = filteredProposals.map(p => [
      p.title,
      p.event_type,
      p.organizer_id,
      p.created_at ? new Date(p.created_at).toLocaleDateString() : "N/A",
      p.venue || "N/A",
      `Rs. ${p.estimated_budget || 0}`,
      p.status.toUpperCase()
    ]);

    autoTable(doc, {
      startY: 42,
      head: [['Event Title', 'Type', 'Organizer ID', 'Date Logged', 'Venue', 'Est. Budget', 'Status']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [16, 185, 129] }, // CampusPulse Emerald (#10B981)
      styles: { fontSize: 9 },
    });

    doc.save(`Event_Proposals_${activeTab}.pdf`);
  };

  // --- CSV (Excel) Export Logic ---
  const handleExportCSV = () => {
    if (filteredProposals.length === 0) {
      alert(`No ${activeTab} proposals to export.`);
      return;
    }

    const headers = ['Event Title', 'Type', 'Organizer ID', 'Date Logged', 'Venue', 'Est. Budget', 'Status'];
    
    const csvRows = filteredProposals.map(p => [
      `"${p.title}"`,
      `"${p.event_type}"`,
      `"${p.organizer_id}"`,
      `"${p.created_at ? new Date(p.created_at).toLocaleDateString() : "N/A"}"`,
      `"${p.venue || "N/A"}"`,
      p.estimated_budget || 0,
      `"${p.status.toUpperCase()}"`
    ].join(','));

    const csvContent = [headers.join(','), ...csvRows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `Event_Proposals_${activeTab}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const containerVars = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { staggerChildren: 0.1 } }
  };

  const itemVars: Variants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 300, damping: 24 } }
  };

  if (loading) return <div className="text-slate-500 font-medium">Loading Approvals Center...</div>;

  return (
    <div className="max-w-6xl mx-auto space-y-10 pb-10">
      
      {/* --- Header & Actions --- */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <motion.div initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }}>
          <h2 className="text-3xl md:text-4xl font-bold text-slate-800 tracking-tight flex items-center gap-3">
            <CalendarCheck className="text-[#10B981]" size={36} />
            Event <span className="text-[#10B981]">Approvals</span>
          </h2>
          <p className="text-slate-500 mt-2">Manage and review all extracurricular proposals for your department.</p>
        </motion.div>

        <motion.div initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} className="flex flex-wrap items-center gap-3">
          <button 
            onClick={handleExportPDF}
            className="bg-[#F5F5F0] text-slate-600 px-5 py-3 rounded-full font-semibold shadow-[8px_8px_16px_rgba(0,0,0,0.05),-8px_-8px_16px_rgba(255,255,255,0.8)] border border-white/60 hover:text-rose-500 transition-colors flex items-center gap-2"
          >
            <FileText size={18} /> Export PDF
          </button>
          <button 
            onClick={handleExportCSV}
            className="bg-[#F5F5F0] text-slate-600 px-5 py-3 rounded-full font-semibold shadow-[8px_8px_16px_rgba(0,0,0,0.05),-8px_-8px_16px_rgba(255,255,255,0.8)] border border-white/60 hover:text-emerald-500 transition-colors flex items-center gap-2"
          >
            <FileSpreadsheet size={18} /> Export Excel
          </button>
        </motion.div>
      </div>

      {/* --- Tabs --- */}
      <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="flex flex-wrap gap-4">
        {(["pending", "approved", "rejected"] as const).map((tab) => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            className={`px-8 py-3 rounded-full font-bold uppercase tracking-widest text-xs transition-all ${
              activeTab === tab
                ? "bg-[#10B981] text-white shadow-lg shadow-[#10B981]/30"
                : "bg-[#F5F5F0] text-slate-500 shadow-[4px_4px_8px_rgba(0,0,0,0.05),-4px_-4px_8px_rgba(255,255,255,0.8)] hover:shadow-[inset_4px_4px_8px_rgba(0,0,0,0.05),inset_-4px_-4px_8px_rgba(255,255,255,0.8)]"
            }`}
          >
            {tab} ({proposals.filter(p => p.status === tab).length})
          </button>
        ))}
      </motion.div>

      {/* --- Proposals List --- */}
      {filteredProposals.length === 0 ? (
        <div className="bg-[#F5F5F0] p-12 rounded-[2rem] shadow-[inset_4px_4px_8px_rgba(0,0,0,0.03),inset_-4px_-4px_8px_rgba(255,255,255,0.8)] text-center text-slate-400 font-medium">
          No {activeTab} event proposals found.
        </div>
      ) : (
        <motion.div variants={containerVars} initial="hidden" animate="show" className="space-y-6">
          {filteredProposals.map((proposal) => (
            <motion.div key={proposal.id} variants={itemVars} className="bg-[#F5F5F0] p-6 md:p-8 rounded-[2rem] shadow-[8px_8px_16px_rgba(0,0,0,0.05),-8px_-8px_16px_rgba(255,255,255,0.8)] border border-white/60">
              
              <div className="flex flex-col lg:flex-row justify-between gap-6">
                {/* Left Side: Details */}
                <div className="space-y-4 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="text-[10px] font-bold uppercase tracking-widest bg-emerald-100 text-emerald-700 px-3 py-1 rounded-full">
                      {proposal.event_type}
                    </span>
                    {proposal.club_name && (
                      <span className="text-[10px] font-bold uppercase tracking-widest bg-purple-100 text-purple-700 px-3 py-1 rounded-full">
                        {proposal.club_name}
                      </span>
                    )}
                    <span className="text-[10px] font-bold uppercase tracking-widest bg-slate-200 text-slate-500 px-3 py-1 rounded-full flex items-center gap-1">
                      <Clock size={12} /> {new Date(proposal.created_at).toLocaleDateString()}
                    </span>
                  </div>
                  
                  <h3 className="text-2xl font-bold text-slate-800">{proposal.title}</h3>
                  <p className="text-slate-600 text-sm leading-relaxed max-w-3xl">{proposal.description}</p>
                  
                  {/* Info Grid */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-4 mt-4 border-t border-slate-200/50">
                    <div className="flex items-center gap-2 text-sm font-medium text-slate-600">
                      <UserCircle className="text-[#10B981]" size={18} />
                      Organizer ID: {proposal.organizer_id}
                    </div>
                    <div className="flex items-center gap-2 text-sm font-medium text-slate-600">
                      <MapPin className="text-rose-400" size={18} />
                      Venue: {proposal.venue}
                    </div>
                    <div className="flex items-center gap-2 text-sm font-medium text-slate-600">
                      <IndianRupee className="text-amber-500" size={18} />
                      Est. Budget: ₹{proposal.estimated_budget}
                    </div>
                    <div className="flex items-center gap-2 text-sm font-medium text-slate-600">
                      <Users className="text-blue-400" size={18} />
                      Audience: {proposal.target_audience} ({proposal.expected_footfall} expected)
                    </div>
                  </div>

                  {/* Additional Meta (Optional Fields) */}
                  {(proposal.guest_speaker || proposal.teacher_coordinator) && (
                    <div className="pt-4 mt-2 space-y-1">
                      {proposal.guest_speaker && (
                        <p className="text-xs text-slate-500"><span className="font-bold">Guest Speaker:</span> {proposal.guest_speaker}</p>
                      )}
                      {proposal.teacher_coordinator && (
                        <p className="text-xs text-slate-500"><span className="font-bold">Teacher Coordinator:</span> {proposal.teacher_coordinator}</p>
                      )}
                    </div>
                  )}
                </div>

                {/* Right Side: Actions or Status Badge */}
                <div className="flex flex-col items-end justify-start min-w-[200px] border-t lg:border-t-0 lg:border-l border-slate-200/50 pt-6 lg:pt-0 lg:pl-6">
                  {activeTab === "pending" ? (
                    <div className="flex flex-col gap-3 w-full">
                      <button 
                        onClick={() => handleApprovalAction(proposal.id, "approved")} 
                        className="w-full flex items-center justify-center gap-2 bg-[#10B981] text-white px-6 py-3 rounded-full font-bold shadow-lg shadow-[#10B981]/30 hover:scale-105 active:scale-95 transition-all"
                      >
                        <CheckCircle size={18} /> Approve
                      </button>
                      <button 
                        onClick={() => handleApprovalAction(proposal.id, "rejected")} 
                        className="w-full flex items-center justify-center gap-2 bg-[#F5F5F0] text-rose-500 px-6 py-3 rounded-full font-bold shadow-[4px_4px_8px_rgba(0,0,0,0.05),-4px_-4px_8px_rgba(255,255,255,0.8)] hover:shadow-[inset_4px_4px_8px_rgba(0,0,0,0.05),inset_-4px_-4px_8px_rgba(255,255,255,0.8)] transition-all"
                      >
                        <XCircle size={18} /> Reject
                      </button>
                    </div>
                  ) : (
                    <div className="w-full flex flex-col items-center justify-center h-full gap-2">
                      {activeTab === "approved" ? (
                        <>
                          <div className="w-16 h-16 rounded-full bg-emerald-100 text-emerald-500 flex items-center justify-center shadow-[inset_2px_2px_4px_rgba(0,0,0,0.05)] mb-2">
                            <CheckCircle size={32} />
                          </div>
                          <span className="text-emerald-500 font-black uppercase tracking-widest text-sm">Approved</span>
                        </>
                      ) : (
                        <>
                          <div className="w-16 h-16 rounded-full bg-rose-100 text-rose-500 flex items-center justify-center shadow-[inset_2px_2px_4px_rgba(0,0,0,0.05)] mb-2">
                            <XCircle size={32} />
                          </div>
                          <span className="text-rose-500 font-black uppercase tracking-widest text-sm">Rejected</span>
                        </>
                      )}
                    </div>
                  )}
                </div>

              </div>
            </motion.div>
          ))}
        </motion.div>
      )}
    </div>
  );
}
