"use client";

import React, { useState, useEffect } from "react";
import { motion, Variants } from "framer-motion";
import { FileText, FileSpreadsheet, Download, Filter, Users, Activity, CheckCircle, Clock, XCircle } from "lucide-react";
import { supabase } from "@/app/student/supabase";
import { useRouter } from "next/navigation";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function DataAndReportsPage() {
  const [filterMode, setFilterMode] = useState<"mentees" | "department">("mentees");
  const [reportsData, setReportsData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  useEffect(() => {
    async function fetchReports() {
      const suid = localStorage.getItem("campuspulse_uid");
      if (!suid) {
        router.replace("/");
        return;
      }

      try {
        // Fetch staff divisions to determine who they mentor
        const { data: coords } = await supabase.from("class_coordinators").select("division").eq("suid", suid);
        const myDivisions = coords?.map(c => c.division) || [];

        // Fetch all students and activities
        const { data: students } = await supabase.from("students").select("uid, name, division");
        const { data: activities } = await supabase.from("student_activities").select("uid, status");

        if (students && activities) {
          const mappedReports = students.map(student => {
            const studentActs = activities.filter(a => a.uid === student.uid);
            const totalLogs = studentActs.length;
            const approved = studentActs.filter(a => a.status === "Approved").length;
            const pending = studentActs.filter(a => a.status === "Pending").length;
            const rejected = studentActs.filter(a => a.status === "Rejected").length;
            
            // Simple engagement metric: 1 log = 10%, capped at 100%
            const engagementNum = Math.min(Math.round((totalLogs / 10) * 100), 100);

            return {
              uid: student.uid,
              name: student.name,
              mentoredByMe: myDivisions.includes(student.division),
              totalLogs,
              approved,
              pending,
              rejected,
              engagement: `${engagementNum}%`,
            };
          });

          // Sort by highest engagement first
          mappedReports.sort((a, b) => parseInt(b.engagement) - parseInt(a.engagement));
          setReportsData(mappedReports);
        }
      } catch (error) {
        console.error("Error fetching reports:", error);
      } finally {
        setLoading(false);
      }
    }
    fetchReports();
  }, [router]);

  const displayedData = filterMode === "mentees" 
    ? reportsData.filter(r => r.mentoredByMe) 
    : reportsData;

  // --- PDF Export Logic ---
  const handleExportPDF = () => {
    if (displayedData.length === 0) {
      alert("No data available to export.");
      return;
    }

    const doc = new jsPDF();
    
    doc.setFontSize(18);
    doc.text("Activity Audit Report", 14, 22);
    
    doc.setFontSize(11);
    doc.setTextColor(100);
    doc.text(`Generated by CampusPulse`, 14, 30);
    doc.text(`Scope: ${filterMode === "mentees" ? "My Mentees" : "Entire Department"}`, 14, 36);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 14, 42);

    const tableData = displayedData.map(r => [
      r.name,
      r.uid,
      r.totalLogs.toString(),
      r.approved.toString(),
      r.pending.toString(),
      r.rejected.toString(),
      r.engagement
    ]);

    autoTable(doc, {
      startY: 48,
      head: [['Student Name', 'UID', 'Total Logs', 'Approved', 'Pending', 'Rejected', 'Engagement']],
      body: tableData,
      theme: 'grid',
      headStyles: { fillColor: [96, 165, 250] }, // CampusPulse Blue (#60A5FA)
      styles: { fontSize: 9 },
    });

    doc.save(`CampusPulse_Audit_${filterMode}.pdf`);
  };

  // --- CSV (Excel) Export Logic ---
  const handleExportCSV = () => {
    if (displayedData.length === 0) {
      alert("No data available to export.");
      return;
    }

    const headers = ['Student Name', 'UID', 'Total Logs', 'Approved', 'Pending', 'Rejected', 'Engagement'];
    
    const csvRows = displayedData.map(r => [
      `"${r.name}"`, // Quoted to prevent issues if a name contains a comma
      `"${r.uid}"`,
      r.totalLogs,
      r.approved,
      r.pending,
      r.rejected,
      `"${r.engagement}"`
    ].join(','));

    const csvContent = [headers.join(','), ...csvRows].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `CampusPulse_Analytics_${filterMode}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const containerVars = {
    hidden: { opacity: 0 },
    show: {
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVars: Variants = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0, transition: { type: "spring", stiffness: 300, damping: 24 } }
  };

  return (
    <div className="max-w-5xl mx-auto">
      
      {/* --- Header --- */}
      <div className="mb-10 flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div>
          <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold text-slate-800 tracking-tight">
            Data & <span className="text-[#60A5FA]">Reports</span>
          </h2>
          <p className="text-slate-500 mt-2">Generate and export activity audits for HOD meetings.</p>
        </div>

        {/* Filter Toggle */}
        <div className="flex items-center bg-[#F5F5F0] p-2 rounded-full shadow-[inset_4px_4px_8px_rgba(0,0,0,0.05),inset_-4px_-4px_8px_rgba(255,255,255,0.8)] self-start md:self-auto w-full sm:w-auto">
          <button 
            onClick={() => setFilterMode("mentees")}
            className={`flex-1 sm:flex-none px-6 py-2.5 rounded-full text-sm font-bold transition-all flex items-center justify-center gap-2 ${filterMode === "mentees" ? 'bg-[#60A5FA] text-white shadow-md shadow-[#60A5FA]/30' : 'text-slate-500 hover:text-slate-700'}`}
          >
            <Filter size={16} /> My Mentees
          </button>
          <button 
            onClick={() => setFilterMode("department")}
            className={`flex-1 sm:flex-none px-6 py-2.5 rounded-full text-sm font-bold transition-all flex items-center justify-center gap-2 ${filterMode === "department" ? 'bg-[#60A5FA] text-white shadow-md shadow-[#60A5FA]/30' : 'text-slate-500 hover:text-slate-700'}`}
          >
            <Users size={16} /> Entire Dept.
          </button>
        </div>
      </div>

      <motion.div variants={containerVars} initial="hidden" animate="show" className="space-y-8">
        
        {/* --- Export Action Cards --- */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          <motion.button 
            variants={itemVars}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handleExportPDF}
            className="bg-[#F5F5F0] p-6 rounded-[2rem] shadow-[8px_8px_16px_rgba(0,0,0,0.05),-8px_-8px_16px_rgba(255,255,255,0.8)] border border-white/60 flex items-center justify-between group"
          >
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-full bg-rose-500/10 text-rose-500 flex items-center justify-center shadow-[inset_2px_2px_4px_rgba(0,0,0,0.02),inset_-2px_-2px_4px_rgba(255,255,255,0.5)]">
                <FileText size={24} />
              </div>
              <div className="text-left">
                <h4 className="font-bold text-slate-700">Export PDF Report</h4>
                <p className="text-xs text-slate-400 font-medium">Formatted for printing</p>
              </div>
            </div>
            <Download size={20} className="text-slate-300 group-hover:text-rose-500 transition-colors" />
          </motion.button>

          <motion.button 
            variants={itemVars}
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={handleExportCSV}
            className="bg-[#F5F5F0] p-6 rounded-[2rem] shadow-[8px_8px_16px_rgba(0,0,0,0.05),-8px_-8px_16px_rgba(255,255,255,0.8)] border border-white/60 flex items-center justify-between group"
          >
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 rounded-full bg-emerald-500/10 text-emerald-500 flex items-center justify-center shadow-[inset_2px_2px_4px_rgba(0,0,0,0.02),inset_-2px_-2px_4px_rgba(255,255,255,0.5)]">
                <FileSpreadsheet size={24} />
              </div>
              <div className="text-left">
                <h4 className="font-bold text-slate-700">Export to Excel</h4>
                <p className="text-xs text-slate-400 font-medium">Raw data & analytics</p>
              </div>
            </div>
            <Download size={20} className="text-slate-300 group-hover:text-emerald-500 transition-colors" />
          </motion.button>
        </div>

        {/* --- Data Preview List --- */}
        <motion.div variants={itemVars} className="bg-[#F5F5F0] p-6 md:p-8 rounded-[2rem] md:rounded-[3rem] shadow-[8px_8px_16px_rgba(0,0,0,0.05),-8px_-8px_16px_rgba(255,255,255,0.8)] border border-white/60">
          <h3 className="text-xl font-bold text-slate-700 mb-6 flex items-center gap-2">
            <Activity size={20} className="text-[#60A5FA]" />
            Data Preview 
            {!loading && <span className="text-sm font-medium text-slate-400 font-normal ml-2">({displayedData.length} Records)</span>}
          </h3>
          
          <div className="space-y-4">
            {loading && <p className="text-slate-500 font-medium py-4">Loading department analytics...</p>}
            {!loading && displayedData.length === 0 && <p className="text-slate-400 py-4">No records found.</p>}
            
            {displayedData.map((student) => (
              <div key={student.uid} className="flex flex-col md:flex-row md:items-center justify-between gap-4 p-5 rounded-2xl bg-[#F5F5F0] shadow-[inset_4px_4px_8px_rgba(0,0,0,0.03),inset_-4px_-4px_8px_rgba(255,255,255,0.8)]">
                
                <div className="flex-1">
                  <h4 className="font-bold text-slate-700">{student.name}</h4>
                  <p className="text-xs text-[#60A5FA] font-medium">{student.uid}</p>
                </div>

                <div className="flex flex-wrap items-center gap-4 md:gap-8">
                  <div className="text-center">
                    <p className="text-[10px] uppercase tracking-widest text-slate-400 font-bold mb-1">Logs</p>
                    <p className="font-bold text-slate-700">{student.totalLogs}</p>
                  </div>
                  <div className="text-center">
                    <p className="text-[10px] uppercase tracking-widest text-slate-400 font-bold mb-1 flex items-center justify-center gap-1"><CheckCircle size={10} className="text-emerald-500"/> Appr.</p>
                    <p className="font-bold text-slate-700">{student.approved}</p>
                  </div>
                  <div className="text-center">
                    <p className="text-[10px] uppercase tracking-widest text-slate-400 font-bold mb-1 flex items-center justify-center gap-1"><Clock size={10} className="text-[#FDBA74]"/> Pend.</p>
                    <p className="font-bold text-slate-700">{student.pending}</p>
                  </div>
                  <div className="text-center">
                    <p className="text-[10px] uppercase tracking-widest text-slate-400 font-bold mb-1 flex items-center justify-center gap-1"><XCircle size={10} className="text-rose-500"/> Rej.</p>
                    <p className="font-bold text-slate-700">{student.rejected}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </motion.div>
      </motion.div>
    </div>
  );
}